import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent, type ReactNode } from 'react'
import { appointments as initialAppointments, contacts as initialContacts, euro, opportunities as initialOpportunities, type Appointment, type Contact, type Opportunity, type Stage } from './data'

type Page = 'Dashboard' | 'Contactos' | 'Oportunidades' | 'Agenda' | 'Reportes'
type Modal = 'contact' | 'opportunity' | 'appointment' | 'settings' | 'notifications' | 'info' | 'menu' | null
type StoredData = { contacts: Contact[]; opportunities: Opportunity[]; appointments: Appointment[] }
const STORAGE_KEY = 'nexo-crm-data'
const nav: { label: Page; icon: string }[] = [['Dashboard', '⌂'], ['Contactos', '♙'], ['Oportunidades', '◒'], ['Agenda', '□'], ['Reportes', '▥']].map(([label, icon]) => ({ label: label as Page, icon }))

function loadStoredData(): StoredData | null {
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY)
    if (!raw) return null
    const value = JSON.parse(raw) as StoredData
    return value.contacts && value.opportunities && value.appointments ? value : null
  } catch {
    return null
  }
}

function Avatar({ initials, color }: { initials: string; color: string }) { return <span className={`avatar ${color}`}>{initials}</span> }
function Badge({ children }: { children: string }) { return <span className={`badge ${children.toLowerCase().replace(/ /g, '-')}`}>{children}</span> }
function Metric({ label, value, trend, tone }: { label: string; value: string; trend?: string; tone: string }) { return <div className="metric"><div className={`metric-icon ${tone}`}>{tone === 'purple' ? '◒' : tone === 'green' ? '↗' : tone === 'orange' ? '€' : '♙'}</div><div><p>{label}</p><strong>{value}</strong>{trend && <small className="positive">{trend}</small>}</div></div> }

function Dashboard({ go, open }: { go: (page: Page) => void; open: (modal: Modal) => void }) {
  const total = initialOpportunities.reduce((sum, item) => sum + item.value, 0)
  return <><div className="welcome"><div><p className="eyebrow">VIERNES, 14 DE JUNIO DE 2024</p><h1>Buenos días, Sergio <span>✦</span></h1><p className="muted">Aquí tienes un resumen de lo que está pasando en tu negocio.</p></div><button className="button primary" onClick={() => open('contact')}>＋ Añadir contacto</button></div>
    <div className="metrics"><Metric label="Contactos totales" value="42" trend="+12.5% vs. mes anterior" tone="purple" /><Metric label="Oportunidades abiertas" value="8" trend="+2 esta semana" tone="green" /><Metric label="Valor del pipeline" value={euro(total + 64400)} trend="+18.4% vs. mes anterior" tone="orange" /><Metric label="Tasa de conversión" value="38%" trend="+4.2% vs. mes anterior" tone="blue" /></div>
    <div className="grid-two"><section className="card"><div className="card-head"><div><h2>Actividad reciente</h2><p className="muted">Últimos movimientos en tu CRM</p></div><button className="link" onClick={() => go('Contactos')}>Ver todo →</button></div><div className="activity"><div className="activity-item"><Avatar initials="AG" color="coral" /><div><b>Ana García</b><span> se ha convertido en cliente</span><small>Hace 2 horas</small></div><span className="activity-value">+ €18.500</span><button className="more" aria-label="Menú de actividad" onClick={() => open('menu')}>•••</button></div><div className="activity-item"><Avatar initials="LM" color="violet" /><div><b>Luis Martín</b><span> ha actualizado una oportunidad</span><small>Hace 5 horas</small></div><span className="activity-value">Propuesta</span><button className="more" aria-label="Menú de actividad" onClick={() => open('menu')}>•••</button></div></div></section>
      <section className="card"><div className="card-head"><div><h2>Próximas citas</h2><p className="muted">No te pierdas nada</p></div><button className="link" onClick={() => go('Agenda')}>Ver agenda →</button></div><div className="appointments">{initialAppointments.slice(0, 3).map(a => <div className="appointment" key={a.id}><div className="date-box"><b>{a.date.split(' ')[1]?.replace(',', '')}</b><small>JUN</small></div><div><b>{a.title}</b><p>{a.time} · {a.contact}</p></div><button className="more" aria-label={`Menú de ${a.title}`} onClick={() => open('menu')}>•••</button></div>)}</div></section></div>
    <section className="card pipeline-card"><div className="card-head"><div><h2>Pipeline de ventas</h2><p className="muted">Estado de tus oportunidades</p></div><button className="link" onClick={() => go('Oportunidades')}>Ver oportunidades →</button></div><div className="pipeline">{(['Prospección', 'Propuesta', 'Negociación', 'Ganada'] as Stage[]).map((stage, i) => <div className="pipe-column" key={stage}><div className="pipe-title"><span className={`dot d${i}`} />{stage}<b>{initialOpportunities.filter(o => o.stage === stage).length}</b></div>{initialOpportunities.filter(o => o.stage === stage).map(o => <div className="deal" key={o.id}><b>{o.title}</b><small>{o.company}</small><strong>{euro(o.value)}</strong></div>)}</div>)}</div></section>
  </>
}

function ContactsPage({ contacts, onCreate, open }: { contacts: Contact[]; onCreate: () => void; open: (modal: Modal) => void }) {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('Todos')
  const filtered = contacts.filter(c => `${c.name} ${c.company} ${c.email}`.toLowerCase().includes(query.toLowerCase()) && (status === 'Todos' || c.status === status))
  return <PageHeader title="Contactos" subtitle="Gestiona tus relaciones y clientes." action="＋ Nuevo contacto" onAction={onCreate}><div className="card table-card"><div className="toolbar"><div className="search">⌕ <input aria-label="Buscar contactos" placeholder="Buscar contactos..." value={query} onChange={e => setQuery(e.target.value)} /></div><label className="filter">Filtrar por <select aria-label="Filtrar contactos" value={status} onChange={e => setStatus(e.target.value)}><option>Todos</option><option>Cliente</option><option>Lead</option><option>Inactivo</option></select></label></div><table><thead><tr><th>CONTACTO</th><th>EMPRESA</th><th>ESTADO</th><th>CONTACTO</th><th /></tr></thead><tbody>{filtered.map(c => <tr key={c.id}><td><div className="person"><Avatar initials={c.initials} color={c.color} /><b>{c.name}</b></div></td><td>{c.company}</td><td><Badge>{c.status}</Badge></td><td><span className="muted">{c.email}</span></td><td><button className="more" aria-label={`Acciones de ${c.name}`} onClick={() => open('menu')}>•••</button></td></tr>)}</tbody></table>{filtered.length === 0 && <p className="empty-state">No hay contactos que coincidan con la búsqueda.</p>}</div></PageHeader>
}

function OpportunitiesPage({ opportunities, onCreate, open }: { opportunities: Opportunity[]; onCreate: () => void; open: (modal: Modal) => void }) {
  const [stage, setStage] = useState('Todas')
  const filtered = opportunities.filter(o => stage === 'Todas' || o.stage === stage)
  return <PageHeader title="Oportunidades" subtitle="Sigue el progreso de tus ventas." action="＋ Nueva oportunidad" onAction={onCreate}><div className="card table-card"><div className="toolbar"><label className="filter">Fase <select aria-label="Filtrar oportunidades" value={stage} onChange={e => setStage(e.target.value)}><option>Todas</option>{(['Prospección', 'Propuesta', 'Negociación', 'Ganada', 'Perdida'] as Stage[]).map(s => <option key={s}>{s}</option>)}</select></label><button className="filter" onClick={() => setStage('Todas')}>Restablecer filtros</button></div><table><thead><tr><th>OPORTUNIDAD</th><th>EMPRESA</th><th>FASE</th><th>CIERRE ESTIMADO</th><th>VALOR</th><th /></tr></thead><tbody>{filtered.map(o => <tr key={o.id}><td><b>{o.title}</b></td><td>{o.company}</td><td><Badge>{o.stage}</Badge></td><td className="muted">{o.close}</td><td><b>{euro(o.value)}</b></td><td><button className="more" aria-label={`Acciones de ${o.title}`} onClick={() => open('menu')}>•••</button></td></tr>)}</tbody></table></div></PageHeader>
}

function AgendaPage({ appointments, onCreate, open }: { appointments: Appointment[]; onCreate: () => void; open: (modal: Modal) => void }) {
  const [selectedDay, setSelectedDay] = useState(14)
  return <PageHeader title="Agenda" subtitle="Organiza tus reuniones y tareas." action="＋ Nueva cita" onAction={onCreate}><div className="agenda-layout"><div className="card calendar"><div className="calendar-head"><button aria-label="Mes anterior" onClick={() => setSelectedDay(Math.max(1, selectedDay - 1))}>‹</button><b>Junio 2024</b><button aria-label="Mes siguiente" onClick={() => setSelectedDay(Math.min(30, selectedDay + 1))}>›</button></div><div className="week">{['L', 'M', 'X', 'J', 'V', 'S', 'D'].map(x => <small key={x}>{x}</small>)}</div><div className="days">{Array.from({ length: 30 }, (_, i) => <button aria-label={`Día ${i + 1}`} className={i + 1 === selectedDay ? 'selected' : i === 17 ? 'has-event' : ''} onClick={() => setSelectedDay(i + 1)} key={i}>{i + 1}</button>)}</div></div><div className="card upcoming"><h2>Próximas citas</h2>{appointments.map(a => <div className="appointment" key={a.id}><div className="date-box"><b>{a.date.split(' ')[1]?.replace(',', '')}</b><small>JUN</small></div><div><b>{a.title}</b><p>{a.time} · {a.contact}</p><small>{a.type}</small></div><button className="more" aria-label={`Acciones de ${a.title}`} onClick={() => open('menu')}>•••</button></div>)}</div></div></PageHeader>
}

function ReportsPage() { const [range, setRange] = useState('Últimos 6 meses'); return <PageHeader title="Reportes" subtitle="Mide el rendimiento de tu negocio."><div className="metrics"><Metric label="Contactos totales" value="42" tone="purple" /><Metric label="Ventas ganadas" value="€64.400" tone="green" /><Metric label="Pipeline actual" value="€125.400" tone="orange" /><Metric label="Tasa de conversión" value="38%" tone="blue" /></div><div className="grid-two"><section className="card chart-card"><div className="card-head"><div><h2>Ingresos por mes</h2><p className="muted">Evolución de los últimos 6 meses</p></div><label className="filter"><select aria-label="Periodo del reporte" value={range} onChange={e => setRange(e.target.value)}><option>Últimos 6 meses</option><option>Este año</option><option>Último mes</option></select></label></div><div className="chart"><div className="chart-y"><span>€40k</span><span>€30k</span><span>€20k</span><span>€10k</span><span>€0</span></div><div className="bars">{[35, 48, 42, 60, 74, 92].map((h, i) => <div className="bar-wrap" key={i}><div className="bar" style={{ height: `${h}%` }} /><small>{['ENE', 'FEB', 'MAR', 'ABR', 'MAY', 'JUN'][i]}</small></div>)}</div></div></section><section className="card"><div className="card-head"><div><h2>Conversión por fase</h2><p className="muted">Tasa de avance</p></div></div><div className="conversion"><div className="ring"><strong>38%</strong><small>global</small></div><div className="legend"><span><i className="dot d0" />Prospección <b>72%</b></span><span><i className="dot d1" />Propuesta <b>54%</b></span><span><i className="dot d2" />Negociación <b>68%</b></span></div></div></section></div></PageHeader> }

function PageHeader({ title, subtitle, action, onAction, children }: { title: string; subtitle: string; action?: string; onAction?: () => void; children?: ReactNode }) { return <><div className="page-heading"><div><h1>{title}</h1><p className="muted">{subtitle}</p></div>{action && <button className="button primary" onClick={onAction}>{action}</button>}</div>{children}</> }

function FormModal({ type, close, onCreate }: { type: Exclude<Modal, null>; close: () => void; onCreate: (type: Exclude<Modal, null>, value: string) => void }) {
  const labels = { contact: ['Nuevo contacto', 'Nombre completo', 'Empresa'], opportunity: ['Nueva oportunidad', 'Título de la oportunidad', 'Empresa'], appointment: ['Nueva cita', 'Título de la cita', 'Contacto'] } as const
  if (!['contact', 'opportunity', 'appointment'].includes(type)) return null
  const [title, field] = labels[type as 'contact' | 'opportunity' | 'appointment']
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); onCreate(type, String(data.get('name') || data.get('title') || field)); close() }
  return <div className="modal-backdrop" role="presentation" onClick={close}><form className="modal" onSubmit={submit} onClick={e => e.stopPropagation()}><button type="button" className="modal-close" aria-label="Cerrar" onClick={close}>×</button><h2>{title}</h2><label>{field}<input required name={type === 'contact' ? 'name' : 'title'} autoFocus /></label><label>{type === 'contact' ? 'Email' : 'Detalles'}<input name="details" placeholder={type === 'contact' ? 'nombre@empresa.com' : 'Información adicional'} /></label><div className="modal-actions"><button type="button" className="filter" onClick={close}>Cancelar</button><button className="button primary">Guardar</button></div></form></div>
}

function InfoModal({ type, close, exportData, importData }: { type: Exclude<Modal, null>; close: () => void; exportData: () => void; importData: (event: ChangeEvent<HTMLInputElement>) => void }) {
  const content = type === 'settings' ? ['Datos de este dispositivo', 'Tus contactos, oportunidades y citas se guardan solo en este navegador. Puedes llevarte una copia JSON o restaurarla aquí.'] : type === 'notifications' ? ['Notificaciones', 'No tienes notificaciones pendientes.'] : type === 'info' ? ['Modo local', 'Esta aplicación funciona sin cuenta ni servidor. Los cambios quedan guardados en este navegador.'] : ['Acciones', 'Selecciona una sección para continuar.']
  return <div className="modal-backdrop" role="presentation" onClick={close}><section className="modal" role="dialog" aria-modal="true" onClick={e => e.stopPropagation()}><button type="button" className="modal-close" aria-label="Cerrar" onClick={close}>×</button><h2>{content[0]}</h2><p className="muted">{content[1]}</p>{type === 'settings' && <div className="data-actions"><button className="filter" onClick={exportData}>↓ Exportar copia JSON</button><label className="filter">↑ Importar copia JSON<input type="file" accept="application/json" onChange={importData} hidden /></label></div>}<div className="modal-actions"><button className="button primary" onClick={close}>Cerrar</button></div></section></div>
}

function App() {
  const [page, setPage] = useState<Page>('Dashboard'); const [mobileOpen, setMobileOpen] = useState(false); const [modal, setModal] = useState<Modal>(null); const [feedback, setFeedback] = useState(''); const [stored] = useState(() => loadStoredData()); const [contacts, setContacts] = useState(stored?.contacts ?? initialContacts); const [opportunities, setOpportunities] = useState(stored?.opportunities ?? initialOpportunities); const [appointments, setAppointments] = useState(stored?.appointments ?? initialAppointments)
  useEffect(() => { window.localStorage.setItem(STORAGE_KEY, JSON.stringify({ contacts, opportunities, appointments })) }, [contacts, opportunities, appointments])
  const notify = (message: string) => { setFeedback(message); window.setTimeout(() => setFeedback(''), 1800) }
  const create = (type: Exclude<Modal, null>, value: string) => {
    const id = Date.now()
    if (type === 'contact') setContacts(current => [...current, { ...initialContacts[0], id, name: value, initials: value.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase() }])
    if (type === 'opportunity') setOpportunities(current => [...current, { ...initialOpportunities[0], id, title: value, value: 0, stage: 'Prospección' }])
    if (type === 'appointment') setAppointments(current => [...current, { ...initialAppointments[0], id, title: value, date: 'Hoy, 14 jun' }])
    notify(`${value} creado correctamente`)
  }
  const exportData = () => {
    const blob = new Blob([JSON.stringify({ contacts, opportunities, appointments }, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'nexo-crm-copia.json'; link.click(); URL.revokeObjectURL(url); notify('Copia JSON descargada')
  }
  const importData = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; if (!file) return
    const reader = new FileReader()
    reader.onload = () => { try { const value = JSON.parse(String(reader.result)) as StoredData; if (!Array.isArray(value.contacts) || !Array.isArray(value.opportunities) || !Array.isArray(value.appointments)) throw new Error('Formato inválido'); setContacts(value.contacts); setOpportunities(value.opportunities); setAppointments(value.appointments); notify('Copia restaurada correctamente'); closeModal() } catch { notify('No se pudo importar la copia') } }
    reader.readAsText(file)
  }
  const closeModal = () => setModal(null)
  const content = useMemo(() => page === 'Dashboard' ? <Dashboard go={setPage} open={setModal} /> : page === 'Contactos' ? <ContactsPage contacts={contacts} onCreate={() => setModal('contact')} open={setModal} /> : page === 'Oportunidades' ? <OpportunitiesPage opportunities={opportunities} onCreate={() => setModal('opportunity')} open={setModal} /> : page === 'Agenda' ? <AgendaPage appointments={appointments} onCreate={() => setModal('appointment')} open={setModal} /> : <ReportsPage />, [page, contacts, opportunities, appointments])
  return <div className="app"><aside className={mobileOpen ? 'open' : ''}><div className="brand"><span className="brand-mark">✦</span><b>nexo<span>crm</span></b></div><button className="workspace" onClick={() => setModal('settings')}><span className="workspace-icon">N</span><div><b>Nexo Studio</b><small>Workspace principal</small></div><span>⌄</span></button><nav>{nav.map(item => <button className={page === item.label ? 'selected' : ''} onClick={() => { setPage(item.label); setMobileOpen(false) }} key={item.label}><i>{item.icon}</i>{item.label}</button>)}</nav><div className="sidebar-bottom"><button onClick={() => setModal('settings')}>⚙ <span>Configuración</span></button><div className="user"><Avatar initials="SP" color="dark" /><div><b>Sergio Pérez</b><small>Administrador</small></div><button aria-label="Menú de usuario" className="more" onClick={() => setModal('menu')}>•••</button></div></div></aside><main><header><button className="menu-button" aria-label="Abrir menú" onClick={() => setMobileOpen(!mobileOpen)}>☰</button><div className="breadcrumbs">Nexo Studio <span>/</span> <b>{page}</b></div><div className="header-actions"><button className="icon-button" aria-label="Buscar contactos" onClick={() => setPage('Contactos')}>⌕</button><button className="icon-button notification" aria-label="Ver notificaciones" onClick={() => setModal('notifications')}>♢<em /></button><div className="header-user"><Avatar initials="SP" color="dark" /><span>SP</span></div></div></header><div className="content"><div className="demo-banner"><span>✦</span><div><b>Modo local</b><span> Tus cambios se guardan en este navegador y dispositivo.</span></div><button onClick={() => setModal('info')}>Más información →</button></div>{content}</div></main>{feedback && <div className="action-feedback" role="status">{feedback}</div>}{modal && (['contact', 'opportunity', 'appointment'].includes(modal) ? <FormModal type={modal} close={closeModal} onCreate={create} /> : <InfoModal type={modal} close={closeModal} exportData={exportData} importData={importData} />)}</div>
}

export default App
