import { useMemo, useState, type ReactNode } from 'react'
import { appointments, contacts, euro, opportunities, type Stage } from './data'
import { hasSupabase } from './env'

type Page = 'Dashboard' | 'Contactos' | 'Oportunidades' | 'Agenda' | 'Reportes'
const nav: { label: Page; icon: string }[] = [['Dashboard', '⌂'], ['Contactos', '♙'], ['Oportunidades', '◒'], ['Agenda', '□'], ['Reportes', '▥']].map(([label, icon]) => ({ label: label as Page, icon }))

function Avatar({ initials, color }: { initials: string; color: string }) { return <span className={`avatar ${color}`}>{initials}</span> }
function Badge({ children }: { children: string }) { return <span className={`badge ${children.toLowerCase().replace(/ /g, '-')}`}>{children}</span> }
function Metric({ label, value, trend, tone }: { label: string; value: string; trend?: string; tone: string }) { return <div className="metric"><div className={`metric-icon ${tone}`}>{tone === 'purple' ? '◒' : tone === 'green' ? '↗' : tone === 'orange' ? '€' : '♙'}</div><div><p>{label}</p><strong>{value}</strong>{trend && <small className="positive">{trend}</small>}</div></div> }

function Dashboard({ go }: { go: (page: Page) => void }) {
  const total = opportunities.reduce((sum, item) => sum + item.value, 0)
  return <><div className="welcome"><div><p className="eyebrow">VIERNES, 14 DE JUNIO DE 2024</p><h1>Buenos días, Sergio <span>✦</span></h1><p className="muted">Aquí tienes un resumen de lo que está pasando en tu negocio.</p></div><button className="button primary" onClick={() => go('Contactos')}>＋ Añadir contacto</button></div>
    <div className="metrics"><Metric label="Contactos totales" value="42" trend="+12.5% vs. mes anterior" tone="purple" /><Metric label="Oportunidades abiertas" value="8" trend="+2 esta semana" tone="green" /><Metric label="Valor del pipeline" value={euro(total + 64400)} trend="+18.4% vs. mes anterior" tone="orange" /><Metric label="Tasa de conversión" value="38%" trend="+4.2% vs. mes anterior" tone="blue" /></div>
    <div className="grid-two"><section className="card"><div className="card-head"><div><h2>Actividad reciente</h2><p className="muted">Últimos movimientos en tu CRM</p></div><button className="link" onClick={() => go('Contactos')}>Ver todo →</button></div><div className="activity"><div className="activity-item"><Avatar initials="AG" color="coral" /><div><b>Ana García</b><span> se ha convertido en cliente</span><small>Hace 2 horas</small></div><span className="activity-value">+ €18.500</span></div><div className="activity-item"><Avatar initials="LM" color="violet" /><div><b>Luis Martín</b><span> ha actualizado una oportunidad</span><small>Hace 5 horas</small></div><span className="activity-value">Propuesta</span></div><div className="activity-item"><Avatar initials="CR" color="amber" /><div><b>Carlos Ruiz</b><span> ha añadido una nota</span><small>Ayer</small></div><span className="activity-value">Nota</span></div></div></section>
      <section className="card"><div className="card-head"><div><h2>Próximas citas</h2><p className="muted">No te pierdas nada</p></div><button className="link" onClick={() => go('Agenda')}>Ver agenda →</button></div><div className="appointments">{appointments.slice(0, 3).map(a => <div className="appointment" key={a.id}><div className="date-box"><b>{a.date.split(' ')[1]?.replace(',', '')}</b><small>JUN</small></div><div><b>{a.title}</b><p>{a.time} · {a.contact}</p></div><span className="more">•••</span></div>)}</div></section></div>
    <section className="card pipeline-card"><div className="card-head"><div><h2>Pipeline de ventas</h2><p className="muted">Estado de tus oportunidades</p></div><button className="link" onClick={() => go('Oportunidades')}>Ver oportunidades →</button></div><div className="pipeline">{(['Prospección', 'Propuesta', 'Negociación', 'Ganada'] as Stage[]).map((stage, i) => <div className="pipe-column" key={stage}><div className="pipe-title"><span className={`dot d${i}`} />{stage}<b>{opportunities.filter(o => o.stage === stage).length}</b></div>{opportunities.filter(o => o.stage === stage).map(o => <div className="deal" key={o.id}><b>{o.title}</b><small>{o.company}</small><strong>{euro(o.value)}</strong></div>)}</div>)}</div></section>
  </>
}

function ContactsPage() { const [query, setQuery] = useState(''); const filtered = contacts.filter(c => `${c.name} ${c.company}`.toLowerCase().includes(query.toLowerCase())); return <PageHeader title="Contactos" subtitle="Gestiona tus relaciones y clientes." action="＋ Nuevo contacto"><div className="card table-card"><div className="toolbar"><div className="search">⌕ <input placeholder="Buscar contactos..." value={query} onChange={e => setQuery(e.target.value)} /></div><button className="filter">Filtrar por ▾</button></div><table><thead><tr><th>CONTACTO</th><th>EMPRESA</th><th>ESTADO</th><th>CONTACTO</th><th /></tr></thead><tbody>{filtered.map(c => <tr key={c.id}><td><div className="person"><Avatar initials={c.initials} color={c.color} /><b>{c.name}</b></div></td><td>{c.company}</td><td><Badge>{c.status}</Badge></td><td><span className="muted">{c.email}</span></td><td className="more">•••</td></tr>)}</tbody></table></div></PageHeader> }
function OpportunitiesPage() { return <PageHeader title="Oportunidades" subtitle="Sigue el progreso de tus ventas." action="＋ Nueva oportunidad"><div className="card table-card"><div className="toolbar"><div className="tabs"><button className="active">Todas <span>8</span></button><button>En progreso <span>6</span></button><button>Ganadas <span>2</span></button></div><button className="filter">Ordenar por ▾</button></div><table><thead><tr><th>OPORTUNIDAD</th><th>EMPRESA</th><th>FASE</th><th>CIERRE ESTIMADO</th><th>VALOR</th></tr></thead><tbody>{opportunities.map(o => <tr key={o.id}><td><b>{o.title}</b></td><td>{o.company}</td><td><Badge>{o.stage}</Badge></td><td className="muted">{o.close}</td><td><b>{euro(o.value)}</b></td></tr>)}</tbody></table></div></PageHeader> }
function AgendaPage() { return <PageHeader title="Agenda" subtitle="Organiza tus reuniones y tareas." action="＋ Nueva cita"><div className="agenda-layout"><div className="card calendar"><div className="calendar-head"><button>‹</button><b>Junio 2024</b><button>›</button></div><div className="week">{['L','M','X','J','V','S','D'].map(x => <small key={x}>{x}</small>)}</div><div className="days">{Array.from({ length: 30 }, (_, i) => <button className={i === 13 ? 'selected' : i === 17 ? 'has-event' : ''} key={i}>{i + 1}</button>)}</div></div><div className="card upcoming"><h2>Próximas citas</h2>{appointments.map(a => <div className="appointment" key={a.id}><div className="date-box"><b>{a.date.split(' ')[1]?.replace(',', '')}</b><small>JUN</small></div><div><b>{a.title}</b><p>{a.time} · {a.contact}</p><small>{a.type}</small></div></div>)}</div></div></PageHeader> }
function ReportsPage() { return <PageHeader title="Reportes" subtitle="Mide el rendimiento de tu negocio."><div className="metrics"><Metric label="Contactos totales" value="42" tone="purple" /><Metric label="Ventas ganadas" value="€64.400" tone="green" /><Metric label="Pipeline actual" value="€125.400" tone="orange" /><Metric label="Tasa de conversión" value="38%" tone="blue" /></div><div className="grid-two"><section className="card chart-card"><div className="card-head"><div><h2>Ingresos por mes</h2><p className="muted">Evolución de los últimos 6 meses</p></div><button className="filter">Últimos 6 meses ▾</button></div><div className="chart"><div className="chart-y"><span>€40k</span><span>€30k</span><span>€20k</span><span>€10k</span><span>€0</span></div><div className="bars">{[35, 48, 42, 60, 74, 92].map((h, i) => <div className="bar-wrap" key={i}><div className="bar" style={{ height: `${h}%` }} /><small>{['ENE','FEB','MAR','ABR','MAY','JUN'][i]}</small></div>)}</div></div></section><section className="card"><div className="card-head"><div><h2>Conversión por fase</h2><p className="muted">Tasa de avance</p></div></div><div className="conversion"><div className="ring"><strong>38%</strong><small>global</small></div><div className="legend"><span><i className="dot d0" />Prospección <b>72%</b></span><span><i className="dot d1" />Propuesta <b>54%</b></span><span><i className="dot d2" />Negociación <b>68%</b></span></div></div></section></div></PageHeader> }
function PageHeader({ title, subtitle, action, children }: { title: string; subtitle: string; action?: string; children: ReactNode }) { return <><div className="page-heading"><div><h1>{title}</h1><p className="muted">{subtitle}</p></div>{action && <button className="button primary">{action}</button>}</div>{children}</> }
function App() { const [page, setPage] = useState<Page>('Dashboard'); const [mobileOpen, setMobileOpen] = useState(false); const content = useMemo(() => page === 'Dashboard' ? <Dashboard go={setPage} /> : page === 'Contactos' ? <ContactsPage /> : page === 'Oportunidades' ? <OpportunitiesPage /> : page === 'Agenda' ? <AgendaPage /> : <ReportsPage />, [page]); return <div className="app"><aside className={mobileOpen ? 'open' : ''}><div className="brand"><span className="brand-mark">✦</span><b>nexo<span>crm</span></b></div><div className="workspace"><span className="workspace-icon">N</span><div><b>Nexo Studio</b><small>Workspace principal</small></div><span>⌄</span></div><nav>{nav.map(item => <button className={page === item.label ? 'selected' : ''} onClick={() => { setPage(item.label); setMobileOpen(false) }} key={item.label}><i>{item.icon}</i>{item.label}</button>)}</nav><div className="sidebar-bottom"><button>⚙ <span>Configuración</span></button><div className="user"><Avatar initials="SP" color="dark" /><div><b>Sergio Pérez</b><small>Administrador</small></div><span>•••</span></div></div></aside><main><header><button className="menu-button" onClick={() => setMobileOpen(!mobileOpen)}>☰</button><div className="breadcrumbs">Nexo Studio <span>/</span> <b>{page}</b></div><div className="header-actions"><button className="icon-button">⌕</button><button className="icon-button notification">♢<em /></button><div className="header-user"><Avatar initials="SP" color="dark" /><span>SP</span></div></div></header><div className="content">{!hasSupabase && <div className="demo-banner"><span>✦</span><div><b>Modo demo</b><span> Estás viendo datos de ejemplo. Conecta Supabase para trabajar con tus datos reales.</span></div><button>Más información →</button></div>}{content}</div></main></div> }
export default App
